"""Implementar metrics types

Revision ID: 251640db6b41
Revises: 56b79619e124
Create Date: 2025-06-16 14:31:51.187453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251640db6b41'
down_revision: Union[str, None] = '56b79619e124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_display_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Enum('STOCK_CERO', 'BAJA_ROTACION', 'STOCK_CRITICO', 'SOBRE_STOCK', 'RECOMENDACION_COMPRA', 'DEVOLUCIONES', 'AJUSTE_STOCK', 'VENTA_SIN_STOCK', name='metricname'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('short_name_2', sa.String(), nullable=True),
    sa.Column('short_name_3', sa.String(), nullable=True),
    sa.Column('short_name_4', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('information_1', sa.Text(), nullable=True),
    sa.Column('information_2', sa.Text(), nullable=True),
    sa.Column('background_color_1', sa.String(length=7), nullable=True),
    sa.Column('text_color_1', sa.String(length=7), nullable=True),
    sa.Column('text_color_2', sa.String(length=7), nullable=True),
    sa.Column('background_color_3', sa.String(length=7), nullable=True),
    sa.Column('text_color_3', sa.String(length=7), nullable=True),
    sa.Column('background_color_4', sa.String(length=7), nullable=True),
    sa.Column('text_color_4', sa.String(length=7), nullable=True),
    sa.Column('show_counter', sa.Boolean(), nullable=False),
    sa.Column('show_grid', sa.Boolean(), nullable=False),
    sa.Column('show_distribution', sa.Boolean(), nullable=False),
    sa.Column('show_products', sa.Boolean(), nullable=False),
    sa.Column('product_operation', sa.String(), nullable=True),
    sa.Column('product_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'metric_id', name='_company_metric_id_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_display_configurations')
    # ### end Alembic commands ###
