"""external_id

Revision ID: 4dc5b63f8755
Revises: daa88da6393b
Create Date: 2025-07-02 15:27:12.160212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc5b63f8755'
down_revision: Union[str, None] = 'daa88da6393b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_external_id'), 'companies', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_external_id'), table_name='companies')
    op.drop_column('companies', 'external_id')
    # ### end Alembic commands ###
