"""Implementar roles de empresa y usar superuser para admin global

Revision ID: caf0676cc2c6
Revises: 86140b41876c
Create Date: 2025-06-15 12:02:49.609575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import enum

# revision identifiers, used by Alembic.
revision: str = 'caf0676cc2c6'
down_revision: Union[str, None] = '86140b41876c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

class CompanyRoleEnum(enum.Enum):
    user = "Usuario"
    company_admin = "Administrador de empresa"

enum_type_name = "companyrole"

def upgrade() -> None:
    """Upgrade schema."""
    company_role_enum = sa.Enum(CompanyRoleEnum, name=enum_type_name)
    company_role_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum(CompanyRoleEnum, name=enum_type_name), nullable=False, server_default='user'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Eliminar la columna
    op.drop_column('users', 'role')

    # 2. Eliminar el tipo ENUM de PostgreSQL
    sa.Enum(CompanyRoleEnum, name=enum_type_name).drop(op.get_bind())
    # ### end Alembic commands ###
