"""Add selectedAvatar to Company table

Revision ID: e80f2d34f740
Revises: 251640db6b41
Create Date: 2025-06-27 20:40:34.003107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80f2d34f740'
down_revision: Union[str, None] = '251640db6b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('selectedAvatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'selectedAvatar')
    # ### end Alembic commands ###
